services:
  - type: web
    name: relatorio-maas
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
